spring:
  application:
    name: ace-lt

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:ace_lt}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${POOL_SIZE:10}
      connection-timeout: 10000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    threads:
      max: 200

poc:
  instance: ${INSTANCE_ID:app-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: WARN
    com.ace.lt: INFO
